/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MinimalContract } from "./MinimalContract";

export { MinimalContract__factory } from "./factories/MinimalContract__factory";
