/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MinimalContract,
  MinimalContractInterface,
} from "../MinimalContract";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122076609a1e4e0092940f6a730484dd5453edb33a86e9b4047710f06b8909b3cfeb64736f6c63430008040033";

type MinimalContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MinimalContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MinimalContract__factory extends ContractFactory {
  constructor(...args: MinimalContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MinimalContract> {
    return super.deploy(overrides || {}) as Promise<MinimalContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MinimalContract {
    return super.attach(address) as MinimalContract;
  }
  connect(signer: Signer): MinimalContract__factory {
    return super.connect(signer) as MinimalContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MinimalContractInterface {
    return new utils.Interface(_abi) as MinimalContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MinimalContract {
    return new Contract(address, _abi, signerOrProvider) as MinimalContract;
  }
}
